title: "Cub Scout Pack 3963"
url: "https://www.pack3963.com"
baseurl: ""

markdown: kramdown
announcement_enabled: true
announcement_link: "/events.html"

exclude:
  - README.md
  - scripts
  - vendor
